### ISSUE TITLE
Node8 build throws error, needs to be precompiled 

### ISSUE THREAD

**Issue by damassi** [nodkz/react-relay-network-modern#10]
When attempting to use the Node 8 version of the lib (for SSR) this error is thrown:

<img width="831" alt="screen shot 2018-01-31 at 9 39 28 pm" src="https://user-images.githubusercontent.com/236943/35662873-6a81505e-06cf-11e8-9ca6-5617ea169523.png">

Looking in the output in `node_modules` folder it appears this code is not being transpiled down like the other builds. Is this intentional? 

I'm currently using Node 9.

**Comment by nodkz** [comment]
It will be fixed in npm after several minutes. Waiting while CI publish a new package.
