### ISSUE TITLE
Documentation Request: Full SSR Example

### ISSUE THREAD

**Issue by damassi** [nodkz/react-relay-network-modern#11]
It would be nice if there was a full, runnable example showing how to work with SSR. For example, in a minimal example such as 

```javascript
import 'isomorphic-fetch'
import 'regenerator-runtime/runtime'
import { Environment, RecordSource, Store } from 'relay-runtime'

// NOTE: 
// This import currently doesn't work out of the box, as the source is not transpiled and 
// `import` statements still exist in output, which Node 8 does not support. 
const RRNL = require('react-relay-network-modern/node8')

const network = new RRNL.RelayNetworkLayer([
  urlMiddleware({ url: "https://metaphysics-staging.artsy.net" }),
])

const source = new RecordSource()
const store = new Store(source)

const relayEnvironment = new Environment({
  network,
  store
})
```

How does one then wire up SSR? Any links / examples / guides would be appreciated.

**Comment by nodkz** [comment]
It very complicated task with relay@1.4 with many hacks. Really cannot find time to write an article.

Shortly, about main hacks...

Just render app two times:
- first time for spinning up queries
- await while network layer executes queries
- render second time with [modified queryRenderer](https://gist.github.com/nodkz/ee25063925ea51a753c4ace7c165c1ef) which takes data from store.

**Comment by damassi** [comment]
Thanks for the gist! 👍 Will investigate further.

**Comment by damassi** [comment]
For those who are curious, I was able to combine a few approaches and swap `react-relay-network-modern` in [here](https://github.com/damassi/isomorphic-relay-app/blob/master/relay-modern/src/lib/isomorphic-relay/getRelayEnvironment.js#L13) and then mount [like so](https://github.com/damassi/isomorphic-relay-app/blob/master/relay-modern/src/apps/artworks/server.js#L17) to achieve SSR. 

(Thanks @robrichard for [the approach](https://github.com/robrichard/relay-modern-isomorphic-example).)

**Comment by nodkz** [comment]
@damassi I just published a new middleware for SSR https://github.com/nodkz/react-relay-network-modern-ssr

Take a look.

**Comment by nodkz** [comment]
@Blackening999 sorry I do not have the public end-to-end example but 
https://github.com/nodkz/react-relay-network-modern
with plugin
https://github.com/nodkz/react-relay-network-modern-ssr
we are using in production.

It's really complex task to describe all nuances and provide simple and ready to use boilerplate. We have a quite difficult setup (babel, webpack, hot-schema-rebuild, hot-server-restrart, hot-reload, splitting with react-loadable, express with a bunch of routes, proxied RelayStore and much more).
 
You may start a public simple demo repo with server/client setup. Where it can be easily started via `yarn start`. And I'll help you to realize SSR on your simple demo app.

Somebody should create a simple isomorphic app in one repo. But I have no time for this.

**Comment by Blackening999** [comment]
@nodkz thank you!
@damassi this is made my day!

looks great!
