### ISSUE TITLE
How to serialize the payload for __RELAY_PAYLOADS__

### ISSUE THREAD

**Issue by cellis** [nodkz/react-relay-network-modern#13]
How can I serialize the json for SSR? Right now I have something like:

```html
<script>
            window.__RELAY_PAYLOADS__ = ${serialize(fetcher, { isJSON: true })};
          </script>
```

And `fetcher.toJson()` simply returns the payloads. But I don't see any way of doing it with this network library.

**Comment by nodkz** [comment]
No elegant solution for your issue right now. But it can be easily fixed.

### You may use existed `cacheMiddleware`:
Internally it uses RelayQueryResponseCache https://github.com/facebook/relay/blob/master/packages/relay-runtime/network/RelayQueryResponseCache.js
```js
let _cache;
return new RRNL.RelayNetworkLayer([
  RRNL.cacheMiddleware({
    size: 100,
    ttl: 900000,
    onInit: cache => (_cache = cache),
  }),
]);

// and somewhere use cached responses
// type ResponseT = {
//   fetchTime: number,
//   payload: GraphQLResponse,
// };
// type ResponsesT = Map<string, ResponseT>;
 
const responses: ResponsesT = _cache._responses;
```

### You may write your custom middleware
```js
return new RRNL.RelayNetworkLayer([
  next => async req => {
    const res = await next(req);

    // here your code
    console.log(req);
    console.log(res);

    return res;
  },
]);
```

### Bonus track: custom middleware for server which serves requests directly from `graphql`
```js
return new RRNL.RelayNetworkLayer([
  () => async req => {
    const res = await graphql({
      schema,
      source: req.getQueryString(),
      variableValues: req.getVariables(),
      contextValue: await this._stores.SSR.getGraphQLContext(),
    });
    return RRNL.RelayNetworkLayerResponse.createFromGraphQL(res);
  },
]);
```

**Comment by nodkz** [comment]
I just published a new middleware for SSR https://github.com/nodkz/react-relay-network-modern-ssr

Take a look.
