### ISSUE TITLE
this._network.observe is not a function

### ISSUE THREAD

**Issue by LaurentHellebrandt** [nodkz/react-relay-network-modern#22]
Hi, in my project I am using
* react: 16.2
* react-dom: 16.2
* react-relay: 1.3

When I use the `RelayNetworkLayer` I get this error.

![bildschirmfoto 2018-04-16 um 13 17 15](https://user-images.githubusercontent.com/6348294/38806126-87a71a9a-4178-11e8-9065-4608a678f19b.png)

This is my code

```
import { Environment, RecordSource, Store } from 'relay-runtime';
import 'regenerator-runtime/runtime';
import { RelayNetworkLayer, authMiddleware } from 'react-relay-network-modern';

const network = new RelayNetworkLayer([
  authMiddleware({
    token: () => 'My Token',
  }),
  next => async req => {
    req.fetchOpts.url = 'Some url';
    req.fetchOpts.credentials = 'include';

    const res = await next(req);
    return res;
  },
]);

const source = new RecordSource();
const store = new Store(source);

const environment = new Environment({
  network,
  store,
});

export default environment;
```

The `environment` created by `new Environment(...)` has the following shape
```
RelayModernEnvironment {
  _network {
    fetchFn: (operation, variables, cacheConfig, uploadables)
  }
}
```

**Comment by LaurentHellebrandt** [comment]
Updated to react-relay 1.5.0 and the error was gone

**Comment by nodkz** [comment]
Thanks for reporting! Also it works under Relay 1.4.0. So if you will have a problem with relay-compiler & recursive max stack trace. Feel free to downgrade react-relay not below 1.4.0.

I checked `package.json` and it has correct peerDependency:
```
"peerDependencies": {
    "relay-runtime": ">=1.4.0"
  },
```
