### ISSUE TITLE
How can i use uploadables on Relay Network Layer for image mutation.

### ISSUE THREAD

**Issue by GaneshPandey** [nodkz/react-relay-network-modern#24]
On Modern Relay we pass uploadables in fetchQuery 

```
fetchQuery(operation, variables, cacheConfig, uploadables) {
  //....
}
```
But how to do it in **RRNM** ?

Here is my environment...

```
const network = new RelayNetworkLayer(middlewares, options);

const store = new Store(new RecordSource());

const environment = new Environment({
  network,
  store,
});
```

**Comment by nodkz** [comment]
It should work out of the box.
See code
https://github.com/nodkz/react-relay-network-modern/blob/650e6cd0c216c5a7cac14154afb044626577a36a/src/RelayRequest.js#L51-L60

When you provide `uploadables` it starts to use `window.FormData` (https://developer.mozilla.org/ru/docs/Web/API/FormData) for packing query and uploadables.

So with your code, it should work in such way:
```js
const network = new RelayNetworkLayer(middlewares, options);
const res = await network.fetchFn(operation, variables, cacheConfig, uploadables);
```

**Comment by GaneshPandey** [comment]
shows error
`await` is a reserved word. Do i need to use polyfill ?

**Comment by nodkz** [comment]
You may use ES5 syntax in such way:
```js
network.fetchFn(operation, variables, cacheConfig, uploadables).toPromise().then(function (res) {
  console.log('completed', res);
});
```
