### ISSUE TITLE
Requires regeneratorRuntime

### ISSUE THREAD

**Issue by brad-decker** [nodkz/react-relay-network-modern#3]
Fails to load due to regeneratorRuntime not being installed. I'm planning on using react-relay-network-modern in a next.js app with SSR and on node 8 this fails due to regeneratorRuntime not being included. I'd like to use native async await when on node 8. Thoughts?

**Comment by nodkz** [comment]
## Now should be published new version with `node8` build for SSR with native async/await.

### Updates in Readme:

#### What if `regeneratorRuntime is not defined`?

I don't want to bundle regenerator-runtime with the library - it's a largish dependency and there's a good chance that the user is already including code which depends on it (eg. via `babel-polyfill`). If we bundle it they'll get a duplicate copy and that's bad.

So if you got `regeneratorRuntime is not defined` you should do the following:
```js
import 'regenerator-runtime/runtime';
import { RelayNetworkLayer } from 'react-relay-network-modern';
```

#### Different builds
This library contains different builds for any purposes:
```js
// Default import for using in any browser
// last 5 versions, ie 9, defaults
import { RelayNetworkLayer } from 'react-relay-network-modern';

// For SSR on node 8 and above (native async/await)
import { RelayNetworkLayer } from 'react-relay-network-modern/node8';

// Source code without Flowtype declarations
import { RelayNetworkLayer } from 'react-relay-network-modern/es';
```

**Comment by brad-decker** [comment]
You're the best @nodkz
