### ISSUE TITLE
lazy cache regeneration.

### ISSUE THREAD

**Issue by graingert** [nodkz/react-relay-network-modern#5]
For some nodes in my graph I'd like them to always update but temporarily show stale data while I'm loading them.

**Comment by nodkz** [comment]
This is not a task for this network layer. It should do Store and QueryRenderer. 

Couple hours ago was released Relay 1.5.0-rc1 maybe it will do what you want, keep in touch with upcoming release notes. 

Anyway you may write custom QueryRenderer with your requirements and take this as reference https://github.com/facebook/relay/blob/master/packages/react-relay/modern/ReactRelayQueryRenderer.js

Or you may take a look on this gist where I create a simple QueryRenderer for server-side
https://gist.github.com/nodkz/ee25063925ea51a753c4ace7c165c1ef
